name: Deploy App

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into the server and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e  # Exit on error
            echo "Deploying from branch: $GITHUB_REF"

            # Go to the backend directory
            cd /home/VAULTIFY_NEW_BACKEND/  


            git fetch origin

            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              echo "Deploying from main branch..."
              git reset --hard origin/main  
            elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
              echo "Deploying from dev branch..."
              git reset --hard origin/dev 
            else
              echo "No deployment action for this branch."
              exit 0  # Exit if the branch is neither main nor dev
            fi


            git clean -fd

            # Pull the latest code
            git pull origin ${{ github.ref }}  # Pull latest code (not strictly necessary after reset)

            # Install dependencies
            npm install  

            # Build the app (if required)
            npm run build  

            # Restart PM2 app
            pm2 restart vaultify-v2
